In [1]:
# Importamos el módulo necesario para trabajar con la base de datos
import pandas as pd
import numpy as np

In [2]:
# Seteamos el directorio donde vamos a trabajar
import os

os.chdir("C:/Users/bauti/OneDrive/Documentos/Escritorio/Big Data/TP2/EPH_usu_1er_Trim_2023_xlsx")

In [3]:
# Cargamos las bases
microdata_hogar = pd.read_excel("usu_hogar_T123.xlsx")

In [4]:
microdata_indv = pd.read_excel("usu_individual_T123.xlsx")

In [5]:

# Del diccionario de variables sabemos que tenemos que quedarnos solamente con los valores 32 y 33
# que son los correspondientes a Ciudad Autónoma de Buenos Aires o Gran Buenos Aires.

# Filtramos el dataframe y lo renombramo
microdata_indv_filtered = microdata_indv[(microdata_indv['AGLOMERADO'] == 32) | (microdata_indv['AGLOMERADO'] == 33)]
len(microdata_indv_filtered)

7619

In [73]:
# Visualizamos las variables para ver cuales son relevantes a la hora de determinar la pobreza

#variables = microdata_hogar.columns
#for variable in variables:
   #print(variable)

In [6]:
# Filtramos el dataframe y lo renombramos
microdata_hogar_filtered = microdata_hogar[(microdata_hogar['AGLOMERADO'] == 32) | (microdata_hogar['AGLOMERADO'] == 33)]
len(microdata_hogar_filtered)

2736

In [12]:
# Realizamos un inner join de las bases para quedarnos solo con las filas cuyo identificador de hogar se encuentre en ambas bases
# Importante remarcar que hacemos el merge por vivienda y hogar! ya que pueden haber 2 viviendas en un mismo hogar.

merged_microdata = microdata_indv_filtered.merge(microdata_hogar_filtered, on=['CODUSU', "NRO_HOGAR"], how='inner')

# Renombrar las columnas con sufijo "_x" a "_indv"
merged_microdata.rename(columns=lambda x: x.replace("_x", "_indv"), inplace=True)

# Renombrar las columnas con sufijo "_y" a "_hogar"
merged_microdata.rename(columns=lambda x: x.replace("_y", "_hogar"), inplace=True)

# Imprimir el DataFrame con las columnas renombradas
print(merged_microdata)

                             CODUSU  ANO4_indv  TRIMESTRE_indv  NRO_HOGAR  \
0     TQRMNORUYHLMSMCDEIJAH00719364       2023               1          1
1     TQRMNORUYHLMSMCDEIJAH00719364       2023               1          1
2     TQRMNOSRQHJNSOCDEIJAH00802640       2023               1          1
3     TQRMNOSRQHJNSOCDEIJAH00802640       2023               1          1
4     TQRMNOSRQHJNSOCDEIJAH00802640       2023               1          1
...                             ...        ...             ...        ...
7614  TQRMNOPVVHKLRQCDEIJAH00780546       2023               1          1
7615  TQRMNOQPTHKKRRCDEIJAH00780327       2023               1          1
7616  TQRMNOPTXHKORSCDEIJAH00780269       2023               1          1
7617  TQRMNOPTXHKORSCDEIJAH00780269       2023               1          1
7618  TQRMNOPTXHKORSCDEIJAH00780269       2023               1          1

      COMPONENTE  H15  REGION_indv MAS_500_indv  AGLOMERADO_indv  \
0              1    1            1            S               33
1              2    1            1            S               33
2              1    1            1            S               33
3              2    1            1            S               33
4              3    0            1            S               33
...          ...  ...          ...          ...              ...
7614           3    0            1            S               33
7615           1    1            1            S               33
7616           1    1            1            S               33
7617           2    1            1            S               33
7618           3    1            1            S               33

      PONDERA_indv  ...  GDECCFR_hogar  PDECCFR_hogar ADECCFR_hogar  \
0             1545  ...            5.0            NaN             6
1             1545  ...            5.0            NaN             6
2             8423  ...            1.0            NaN             1
3             8423  ...            1.0            NaN             1
4             8423  ...            1.0            NaN             1
...            ...  ...            ...            ...           ...
7614          1236  ...            9.0            NaN             9
7615          1300  ...           10.0            NaN            10
7616          1193  ...           12.0            NaN            12
7617          1193  ...           12.0            NaN            12
7618          1193  ...           12.0            NaN            12

      PONDIH_hogar  VII1_1  VII1_2  VII2_1  VII2_2  VII2_3  VII2_4
0             2540       1       0       2       0       0       0
1             2540       1       0       2       0       0       0
2            14082       2       1      98       0       0       0
3            14082       2       1      98       0       0       0
4            14082       2       1      98       0       0       0
...            ...     ...     ...     ...     ...     ...     ...
7614          2295       1       2      98       0       0       0
7615          1516       1       0      96       0       0       0
7616             0       1       2       3       0       0       0
7617             0       1       2       3       0       0       0
7618             0       1       2       3       0       0       0

[7619 rows x 263 columns]

In [8]:
# Chequeamos la dimension
len(merged_microdata)

7619

In [15]:
# Visualizamos las variables para ver que limpiar

variables = merged_microdata.columns
for variable in variables:
   print(variable)

CODUSU
ANO4_indv
TRIMESTRE_indv
NRO_HOGAR
COMPONENTE
H15
REGION_indv
MAS_500_indv
AGLOMERADO_indv
PONDERA_indv
CH03
CH04
CH05
CH06
CH07
CH08
CH09
CH10
CH11
CH12
CH13
CH15
CH16
NIVEL_ED
ESTADO
CAT_OCUP
CAT_INAC
PP02C1
PP02C2
PP02C3
PP02C4
PP02C5
PP02C6
PP02C7
PP02C8
PP02E
PP02H
PP02I
P21
DECOCUR
RDECOCUR
GDECOCUR
ADECOCUR
PONDIIO
TOT_P12
P47T
DECINDR
RDECINDR
GDECINDR
ADECINDR
PONDII
V2_M
V3_M
V4_M
V5_M
V8_M
V9_M
V10_M
V11_M
V12_M
V18_M
V19_AM
V21_M
T_VI
ITF_indv
DECIFR_indv
RDECIFR_indv
GDECIFR_indv
ADECIFR_indv
IPCF_indv
DECCFR_indv
RDECCFR_indv
GDECCFR_indv
ADECCFR_indv
PONDIH_indv
ANO4_hogar
TRIMESTRE_hogar
REALIZADA
REGION_hogar
MAS_500_hogar
AGLOMERADO_hogar
PONDERA_hogar
IV1
IV2
IV3
IV4
IV5
IV6
IV7
IV8
IV9
IV10
IV11
IV12_1
IV12_2
IV12_3
II1
II2
II3
II3_1
II4_1
II4_2
II4_3
II5
II5_1
II6
II6_1
II7
II8
II9
V1
V2
V21
V22
V3
V4
V5
V6
V7
V8
V9
V10
V11
V12
V13
V14
V15
V16
V17
V18
V19_A
V19_B
IX_TOT
IX_MEN10
IX_MAYEQ10
ITF_hogar
DECIFR_hogar
RDECIFR_hogar
GDECIFR_hogar
ADECIFR_hogar
IPCF_hogar
DECCFR_hogar
RDECCFR_hogar
GDECCFR_hogar
ADECCFR_hogar
PONDIH_hogar
VII1_1
VII1_2
VII2_1
VII2_2
VII2_3
VII2_4

In [91]:
# Identificar variables con NaN y contar cuántos NaN
variables_con_nan = merged_microdata.columns[merged_microdata.isna().any()].tolist()
conteo_de_nans = merged_microdata[variables_con_nan].isna().sum()

# Imprimir las variables con NaN y la cantidad de NaN en cada una
for variable in variables_con_nan:
    print(f'Variable: {variable}, Cantidad de NaN: {conteo_de_nans[variable]}')

Variable: IV1_ESP, Cantidad de NaN: 7602
Variable: IV3_ESP, Cantidad de NaN: 7608
Variable: IV7_ESP, Cantidad de NaN: 7605
Variable: II7_ESP, Cantidad de NaN: 7590
Variable: II8_ESP, Cantidad de NaN: 7392
Variable: IDECIFR_x, Cantidad de NaN: 7619
Variable: PDECIFR_x, Cantidad de NaN: 7619
Variable: IDECCFR_x, Cantidad de NaN: 7619
Variable: PDECCFR_x, Cantidad de NaN: 7619
Variable: CH08, Cantidad de NaN: 1
Variable: CH14, Cantidad de NaN: 3959
Variable: CH15_COD, Cantidad de NaN: 6248
Variable: CH16_COD, Cantidad de NaN: 7515
Variable: IMPUTA, Cantidad de NaN: 7548
Variable: PP03C, Cantidad de NaN: 4096
Variable: PP03D, Cantidad de NaN: 4096
Variable: PP3E_TOT, Cantidad de NaN: 4096
Variable: PP3F_TOT, Cantidad de NaN: 4096
Variable: PP03G, Cantidad de NaN: 4096
Variable: PP03H, Cantidad de NaN: 4096
Variable: PP03I, Cantidad de NaN: 4096
Variable: PP03J, Cantidad de NaN: 4096
Variable: INTENSI, Cantidad de NaN: 4096
Variable: PP04A, Cantidad de NaN: 4096
Variable: PP04B_COD, Cantidad de NaN: 4096
Variable: PP04B1, Cantidad de NaN: 4096
Variable: PP04B2, Cantidad de NaN: 4096
Variable: PP04B3_MES, Cantidad de NaN: 4096
Variable: PP04B3_ANO, Cantidad de NaN: 4096
Variable: PP04B3_DIA, Cantidad de NaN: 4096
Variable: PP04C, Cantidad de NaN: 4096
Variable: PP04C99, Cantidad de NaN: 4096
Variable: PP04D_COD, Cantidad de NaN: 4096
Variable: PP04G, Cantidad de NaN: 4096
Variable: PP05B2_MES, Cantidad de NaN: 4096
Variable: PP05B2_ANO, Cantidad de NaN: 4096
Variable: PP05B2_DIA, Cantidad de NaN: 4096
Variable: PP05C_1, Cantidad de NaN: 4096
Variable: PP05C_2, Cantidad de NaN: 4096
Variable: PP05C_3, Cantidad de NaN: 4096
Variable: PP05E, Cantidad de NaN: 4096
Variable: PP05F, Cantidad de NaN: 4096
Variable: PP05H, Cantidad de NaN: 4096
Variable: PP06A, Cantidad de NaN: 4096
Variable: PP06C, Cantidad de NaN: 4096
Variable: PP06D, Cantidad de NaN: 4096
Variable: PP06E, Cantidad de NaN: 4096
Variable: PP06H, Cantidad de NaN: 4096
Variable: PP07A, Cantidad de NaN: 4096
Variable: PP07C, Cantidad de NaN: 4096
Variable: PP07D, Cantidad de NaN: 4096
Variable: PP07E, Cantidad de NaN: 4096
Variable: PP07F1, Cantidad de NaN: 4096
Variable: PP07F2, Cantidad de NaN: 4096
Variable: PP07F3, Cantidad de NaN: 4096
Variable: PP07F4, Cantidad de NaN: 4096
Variable: PP07F5, Cantidad de NaN: 4096
Variable: PP07G1, Cantidad de NaN: 4096
Variable: PP07G2, Cantidad de NaN: 4096
Variable: PP07G3, Cantidad de NaN: 4096
Variable: PP07G4, Cantidad de NaN: 4096
Variable: PP07G_59, Cantidad de NaN: 4096
Variable: PP07H, Cantidad de NaN: 4096
Variable: PP07I, Cantidad de NaN: 4096
Variable: PP07J, Cantidad de NaN: 4096
Variable: PP07K, Cantidad de NaN: 4096
Variable: PP08D1, Cantidad de NaN: 4096
Variable: PP08D4, Cantidad de NaN: 4096
Variable: PP08F1, Cantidad de NaN: 4096
Variable: PP08F2, Cantidad de NaN: 4096
Variable: PP08J1, Cantidad de NaN: 4096
Variable: PP08J2, Cantidad de NaN: 4096
Variable: PP08J3, Cantidad de NaN: 4096
Variable: PP09A, Cantidad de NaN: 4096
Variable: PP09A_ESP, Cantidad de NaN: 7602
Variable: PP09B, Cantidad de NaN: 4096
Variable: PP09C, Cantidad de NaN: 4096
Variable: PP09C_ESP, Cantidad de NaN: 7619
Variable: PP10A, Cantidad de NaN: 7333
Variable: PP10C, Cantidad de NaN: 7333
Variable: PP10D, Cantidad de NaN: 7333
Variable: PP10E, Cantidad de NaN: 7333
Variable: PP11A, Cantidad de NaN: 7333
Variable: PP11B_COD, Cantidad de NaN: 7333
Variable: PP11B1, Cantidad de NaN: 7333
Variable: PP11B2_MES, Cantidad de NaN: 7333
Variable: PP11B2_ANO, Cantidad de NaN: 7333
Variable: PP11B2_DIA, Cantidad de NaN: 7333
Variable: PP11C, Cantidad de NaN: 7333
Variable: PP11C99, Cantidad de NaN: 7333
Variable: PP11D_COD, Cantidad de NaN: 7410
Variable: PP11G_ANO, Cantidad de NaN: 7333
Variable: PP11G_MES, Cantidad de NaN: 7333
Variable: PP11G_DIA, Cantidad de NaN: 7333
Variable: PP11L, Cantidad de NaN: 7333
Variable: PP11L1, Cantidad de NaN: 7333
Variable: PP11M, Cantidad de NaN: 7333
Variable: PP11N, Cantidad de NaN: 7333
Variable: PP11O, Cantidad de NaN: 7333
Variable: PP11P, Cantidad de NaN: 7333
Variable: PP11Q, Cantidad de NaN: 7333
Variable: PP11R, Cantidad de NaN: 7333
Variable: PP11S, Cantidad de NaN: 7333
Variable: PP11T, Cantidad de NaN: 7333
Variable: IDECOCUR, Cantidad de NaN: 7619
Variable: PDECOCUR, Cantidad de NaN: 7619
Variable: P47T, Cantidad de NaN: 24
Variable: IDECINDR, Cantidad de NaN: 7619
Variable: PDECINDR, Cantidad de NaN: 7619
Variable: IDECIFR_y, Cantidad de NaN: 7619
Variable: PDECIFR_y, Cantidad de NaN: 7619
Variable: IDECCFR_y, Cantidad de NaN: 7619
Variable: PDECCFR_y, Cantidad de NaN: 7619

In [14]:
# Establecer el umbral de 7500 para determinar qué columnas eliminar
umbral = 7500

# Eliminar columnas con más de 7500 valores NaN
merged_microdata = merged_microdata.dropna(thresh=umbral, axis=1)
merged_microdata.head(2)

,CODUSU,ANO4_indv,TRIMESTRE_indv,NRO_HOGAR,COMPONENTE,H15,REGION_indv,MAS_500_indv,AGLOMERADO_indv,PONDERA_indv,...,RDECCFR_hogar,GDECCFR_hogar,ADECCFR_hogar,PONDIH_hogar,VII1_1,VII1_2,VII2_1,VII2_2,VII2_3,VII2_4
0,TQRMNORUYHLMSMCDEIJAH00719364,2023,1,1,1,1,1,S,33,1545,...,5,5.0,6,2540,1,0,2,0,0,0
1,TQRMNORUYHLMSMCDEIJAH00719364,2023,1,1,2,1,1,S,33,1545,...,5,5.0,6,2540,1,0,2,0,0,0

In [22]:
# Obtener estadísticas descriptivas de la variable de interes.
estadisticas_descriptivas1 = merged_microdata['ITF_indv'].describe()
estadisticas_descriptivas2 = merged_microdata[''].describe()
estadisticas_descriptivas3 = merged_microdata[''].describe()
estadisticas_descriptivas4 = merged_microdata[''].describe()
estadisticas_descriptivas5 = merged_microdata[''].describe()

# Imprimir las estadísticas descriptivas
print(estadisticas_descriptivas1)
print(estadisticas_descriptivas2)
print(estadisticas_descriptivas3)
print(estadisticas_descriptivas4)
print(estadisticas_descriptivas5)

count    7.619000e+03
mean     1.384079e+05
std      3.349417e+05
min      0.000000e+00
25%      0.000000e+00
50%      7.500000e+04
75%      2.000000e+05
max      1.099000e+07
Name: ITF_indv, dtype: float64

In [16]:
# Armamos una función para no tener que lidiar con el tedioso uso del archivo de Excel.

# Esta función, asignar_valor, toma dos argumentos, edad y genero, y asigna un valor numérico basado en reglas condicionales
# que dependen de estos dos argumentos. Las condiciones se prueban en orden y, cuando se encuentra una coincidencia, se
# devuelve un valor específico. Si no se cumple ninguna condición, la función devuelve None.
#Las condiciones están diseñadas para categorizar a las personas en grupos según su edad y género y asignarles un valor numérico basado en esas categorías.

def asignar_valor(edad, genero):
    if edad < 1:
        if genero == 2:
            return 0.35
        elif genero == 1:
            return 0.35
    elif edad == 1:
        if genero == 2:
            return 0.37
        elif genero == 1:
            return 0.37
    elif edad == 2:
        if genero == 2:
            return 0.46
        elif genero == 1:
            return 0.46
    elif edad == 3:
        if genero == 2:
            return 0.51
        elif genero == 1:
            return 0.51
    elif edad == 4:
        if genero == 2:
            return 0.55
        elif genero == 1:
            return 0.55
    elif edad == 5:
        if genero == 2:
            return 0.60
        elif genero == 1:
            return 0.60
    elif edad == 6:
        if genero == 2:
            return 0.64
        elif genero == 1:
            return 0.64
    elif edad == 7:
        if genero == 2:
            return 0.66
        elif genero == 1:
            return 0.66
    elif edad == 8:
        if genero == 2:
            return 0.68
        elif genero == 1:
            return 0.68
    elif edad == 9:
        if genero == 2:
            return 0.69
        elif genero == 1:
            return 0.69
    elif edad == 10:
        if genero == 2:
            return 0.70
        elif genero == 1:
            return 0.79
    elif edad == 11:
        if genero == 2:
            return 0.72
        elif genero == 1:
            return 0.82
    elif edad == 12:
        if genero == 2:
            return 0.74
        elif genero == 1:
            return 0.85
    elif edad == 13:
        if genero == 2:
            return 0.76
        elif genero == 1:
            return 0.90
    elif edad == 14:
        if genero == 2:
            return 0.76
        elif genero == 1:
            return 0.96
    elif edad == 15:
        if genero == 2:
            return 0.77
        elif genero == 1:
            return 1.00
    elif edad == 16:
        if genero == 2:
            return 0.77
        elif genero == 1:
            return 1.03
    elif edad == 17:
        if genero == 2:
            return 0.77
        elif genero == 1:
            return 1.04
    elif 18 <= edad <= 29:
        if genero == 2:
            return 0.76
        elif genero == 1:
            return 1.02
    elif 30 <= edad <= 45:
        if genero == 2:
            return 0.77
        elif genero == 1:
            return 1.00
    elif 46 <= edad <= 60:
        if genero == 2:
            return 0.76
        elif genero == 1:
            return 1.00
    elif 61 <= edad <= 75:
        if genero == 2:
            return 0.67
        elif genero == 1:
            return 0.83
    elif edad > 75:
        if genero == 2:
            return 0.63
        elif genero == 1:
            return 0.74
    else:
        return None  # En caso de que no haya una combinación válida

In [17]:
# Aplicamos la funcion al data frame. Creamos una nueva columna llamada 'adulto_equiv' en el DataFrame 'microdata_filtered', donde se calculan y asignan valores equivalentes para adultos
# a partir de las edades ('CH06') y géneros ('CH04') de cada fila utilizando una función llamada 'asignar_valor'.

merged_microdata['adulto_equiv'] = merged_microdata.apply(lambda row: asignar_valor(row['CH06'], row['CH04']), axis=1)

In [18]:
merged_microdata

,CODUSU,ANO4_indv,TRIMESTRE_indv,NRO_HOGAR,COMPONENTE,H15,REGION_indv,MAS_500_indv,AGLOMERADO_indv,PONDERA_indv,...,GDECCFR_hogar,ADECCFR_hogar,PONDIH_hogar,VII1_1,VII1_2,VII2_1,VII2_2,VII2_3,VII2_4,adulto_equiv
0,TQRMNORUYHLMSMCDEIJAH00719364,2023,1,1,1,1,1,S,33,1545,...,5.0,6,2540,1,0,2,0,0,0,0.67
1,TQRMNORUYHLMSMCDEIJAH00719364,2023,1,1,2,1,1,S,33,1545,...,5.0,6,2540,1,0,2,0,0,0,0.83
2,TQRMNOSRQHJNSOCDEIJAH00802640,2023,1,1,1,1,1,S,33,8423,...,1.0,1,14082,2,1,98,0,0,0,1.00
3,TQRMNOSRQHJNSOCDEIJAH00802640,2023,1,1,2,1,1,S,33,8423,...,1.0,1,14082,2,1,98,0,0,0,0.76
4,TQRMNOSRQHJNSOCDEIJAH00802640,2023,1,1,3,0,1,S,33,8423,...,1.0,1,14082,2,1,98,0,0,0,0.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7614,TQRMNOPVVHKLRQCDEIJAH00780546,2023,1,1,3,0,1,S,33,1236,...,9.0,9,2295,1,2,98,0,0,0,0.69
7615,TQRMNOQPTHKKRRCDEIJAH00780327,2023,1,1,1,1,1,S,33,1300,...,10.0,10,1516,1,0,96,0,0,0,0.63
7616,TQRMNOPTXHKORSCDEIJAH00780269,2023,1,1,1,1,1,S,33,1193,...,12.0,12,0,1,2,3,0,0,0,0.77
7617,TQRMNOPTXHKORSCDEIJAH00780269,2023,1,1,2,1,1,S,33,1193,...,12.0,12,0,1,2,3,0,0,0,1.04
7618,TQRMNOPTXHKORSCDEIJAH00780269,2023,1,1,3,1,1,S,33,1193,...,12.0,12,0,1,2,3,0,0,0,1.02

In [19]:
# Limpiamos y Renombramos

merged_microdata = merged_microdata.dropna(subset=['adulto_equiv'])

result = merged_microdata.groupby(by=['CODUSU','NRO_HOGAR']).agg({'adulto_equiv': 'sum'}).reset_index()
result.rename(columns={'adulto_equiv': 'ad_equiv_hogar'}, inplace=True)

merged_microdata_FINAL = pd.merge(merged_microdata, result[['CODUSU','NRO_HOGAR', 'ad_equiv_hogar']],
                     on=['CODUSU','NRO_HOGAR'],
                     how='left')

In [26]:
# Definimos ambas bases según los criterios del enunciado, comprobando la condición sobre ITF.
# Imprimimos la longitud del DataFrame para obtener las cantidades.

# Reemplazar NaN por ceros en ITF_indv e ITF_hogar
merged_microdata['ITF_indv'].fillna(0, inplace=True)
merged_microdata['ITF_hogar'].fillna(0, inplace=True)

respondieron = merged_microdata_FINAL[(merged_microdata_FINAL['ITF_indv'] != 0) | (merged_microdata_FINAL['ITF_hogar'] != 0)]
print(len(respondieron))

norespondieron = merged_microdata_FINAL[(merged_microdata_FINAL['ITF_indv'] == 0) & (merged_microdata_FINAL['ITF_hogar'] == 0)]
print(len(norespondieron))

4214
3405

In [27]:
# Definimos el valor de la canasta básica y luego
# seguimos las instrucciones del enunciado para añadir una columna que indique el ingreso necesario

valor_canasta_basica = 57371.05

respondieron['ingreso_necesario'] = respondieron['ad_equiv_hogar'] * valor_canasta_basica

C:\Users\bauti\AppData\Local\Temp/ipykernel_7588/3528590793.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  respondieron['ingreso_necesario'] = respondieron['ad_equiv_hogar'] * valor_canasta_basica

In [28]:
# Creamos una nueva columna llamada 'pobre' en el DataFrame 'respondieron',
# donde se asigna un valor de 1 si el valor en la columna 'ITF' es menor que
# el valor en la columna 'ingreso_necesario', y 0 en caso contrario, convirtiendo los resultados a enteros.

respondieron['pobre'] = ((respondieron['ITF_hogar'] < respondieron['ingreso_necesario']) & (respondieron['ITF_indv'] < respondieron['ingreso_necesario'])).astype(int)

# Sumamos todos los 1

num_pobres = respondieron['pobre'].sum()

print(f'Número de pobres identificados: {num_pobres}')

# En %

print(num_pobres/len(respondieron))

Número de pobres identificados: 1577
0.37422876127195065

C:\Users\bauti\AppData\Local\Temp/ipykernel_7588/2894708243.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  respondieron['pobre'] = ((respondieron['ITF_hogar'] < respondieron['ingreso_necesario']) & (respondieron['ITF_indv'] < respondieron['ingreso_necesario'])).astype(int)

In [30]:
merged_microdata_FINAL['PONDIH_hogar']

0        2540
1        2540
2       14082
3       14082
4       14082
        ...
7614     2295
7615     1516
7616        0
7617        0
7618        0
Name: PONDIH_hogar, Length: 7619, dtype: int64

In [42]:
# Agrupar por hogar y utilizar el ponderador PONDIH para calcular la tasa de hogares pobres
tasa_pobreza_gba = (respondieron.groupby(['CODUSU', 'NRO_HOGAR'])['pobre'].max() * respondieron.groupby('CODUSU')['PONDIH_hogar'].max()).sum() / respondieron['PONDIH_hogar'].sum()

# Imprimir el resultado
print("Tasa de hogares bajo la línea de pobreza en el GBA:", tasa_pobreza_gba)

Tasa de hogares bajo la línea de pobreza en el GBA: 0.09629288459759894